run:
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

